export const TOGGLE_PANEL = 'TOGGLE_PANEL';
export const OPEN_PANEL = 'OPEN_PANEL';
export const ADD_CART = 'ADD_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const FILTER = 'FILTER';
export const CLOSE_PANEL = 'CLOSE_PANEL';
export const INCREMENT_PRODUCT_IN_BASKET = 'INCREMENT_PRODUCT_IN_BASKET';
export const DECREMENT_PRODUCT_IN_BASKET = 'DECREMENT_PRODUCT_IN_BASKET';
